version: "3.8"

services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance-core
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./trades.db:/app/trades.db

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance-dashboard
    restart: always
    command: >
      streamlit run dashboard.py
        --server.port 8501
        --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./logs:/app/logs
